### ISSUE TITLE
Mesh picking not working

### ISSUE THREAD

**Issue by smfloery** [smfloery/moniQue#18]
Picking of GCPs in object space didnt work. As it seems when using pygfx 0.20.0 material.pick_write per default is False. See https://github.com/pygfx/pygfx/releases

**Comment by dsimboeck** [comment]
Fixed the issue by manually enabling picking (material.pick_write = True) in line 408 of "dlg_main.py".
Update was pushed to dsimboeck/moniQue: 471bd48fb77f99d5ac59d7101251b4ccb38ad089
